services:
  scheduler-air:
    image: cosmtrek/air
    working_dir: /scheduler
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
      - ./scheduler:/scheduler

  db:
    container_name: scheduler_db
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - net

volumes:
  postgres_data:

networks:
  net:
    name: net
    driver: bridge